[package]
name = "rust-indexer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust-indexer"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
